=== asdpboy/cobarclient-hibernate/src/main/resources/rules.dtd
<?xml version="1.0"  encoding="UTF-8"?>

<!ELEMENT rules (rule)+>

<!ELEMENT rule ((className|methodName),shardingExpression,shards)>

<!ELEMENT className (#PCDATA)>

<!ELEMENT methodName (#PCDATA)>

<!ELEMENT shardingExpression (#PCDATA)>

<!ELEMENT shards (#PCDATA)>

=== asdpboy/cobarclient-hibernate/src/test/java/META-INF/routing/classname-only-rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rules SYSTEM "rules.dtd">
<rules>
  <rule>
    <className>com.alibaba.cobar.client.entities.Depart</className>
    <shards>partition2</shards>
  </rule>
  <rule>
    <className>com.alibaba.cobar.client.entities.Role</className>
    <shards>partition1</shards>
  </rule>
    <rule>
    <className>com.alibaba.cobar.client.entities.Offer</className>
    <shards>partition1</shards>
  </rule>
</rules>
